basePath: /api/v1
definitions:
  dto.CreateFieldRequest:
    properties:
      active:
        type: boolean
      code:
        type: string
      form_id:
        type: string
      name:
        type: string
      type_id:
        type: integer
    type: object
  dto.CreateFormRequest:
    properties:
      active:
        type: boolean
      fields:
        items:
          $ref: '#/definitions/dto.CreateFieldRequest'
        type: array
      name:
        type: string
    type: object
  dto.FieldResponse:
    properties:
      active:
        type: boolean
      code:
        type: string
      date_create:
        type: string
      date_update:
        type: string
      form_id:
        type: string
      id:
        type: string
      name:
        type: string
      type_id:
        type: integer
    type: object
  dto.FormResponse:
    properties:
      active:
        type: boolean
      date_create:
        type: string
      date_update:
        type: string
      fields:
        items:
          $ref: '#/definitions/dto.FieldResponse'
        type: array
      id:
        type: string
      name:
        type: string
    type: object
  response.Error:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: sholokhovdaniil@yandex.ru
    name: API Support
    url: https://t.me/sholokhov22
  description: API for interacting with feedback forms
  termsOfService: http://swagger.io/terms/
  title: Feedback form API
  version: "1.0"
paths:
  /forms:
    get:
      consumes:
      - application/json
      description: Returns all available forms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.FormResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/response.Error'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/response.Error'
            type: array
      security:
      - BearerAuth: []
      summary: List feedback forms
      tags:
      - forms
    post:
      consumes:
      - application/json
      description: Creates a new form for a specific user
      parameters:
      - description: Form creation data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateFormRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FormResponse'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/response.Error'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/response.Error'
            type: array
      security:
      - BearerAuth: []
      summary: Creates a new form
      tags:
      - forms
  /forms/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Form ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FormResponse'
        "404":
          description: Not Found
          schema:
            items:
              $ref: '#/definitions/response.Error'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/response.Error'
            type: array
      summary: Returns a specific user form by its ID
      tags:
      - forms
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
